# -*- coding: utf-8 -*-
"""Codeveda Risk Analysis ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFMDJPbZ-FqxPeUMgIbYCt4RkS_JwBMF
"""

# Install and import all libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (accuracy_score, classification_report,
                             confusion_matrix, mean_squared_error, r2_score)
import warnings
warnings.filterwarnings('ignore')

print("All libraries loaded successfully!")

from google.colab import files
uploaded = files.upload()
# Upload both: churn-bigml-80.csv and churn-bigml-20.csv when prompted

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier, IsolationForest
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve

# Load datasets
train_df = pd.read_csv('churn-bigml-80.csv')  # 80% training set
test_df = pd.read_csv('churn-bigml-20.csv')   # 20% test set

print(train_df.shape, test_df.shape)
print(train_df.head())
print(train_df.info())

# Encode binary/categorical columns
le = LabelEncoder()

for df in [train_df, test_df]:
    for col in df.select_dtypes(include='object').columns:
        df[col] = le.fit_transform(df[col])
    for col in df.select_dtypes(include='bool').columns:
        df[col] = df[col].astype(int)

print("Missing values:", train_df.isnull().sum().sum())
print(train_df['Churn'].value_counts())

sns.countplot(x='Churn', data=train_df, palette='Set2')
plt.title('Churn Distribution (0 = No, 1 = Yes)')
plt.show()

# Correlation heatmap
plt.figure(figsize=(14, 10))
sns.heatmap(train_df.corr(), annot=False, cmap='coolwarm')
plt.title('Feature Correlation Heatmap')
plt.show()

# Use numeric features only
features = train_df.drop('Churn', axis=1)

iso = IsolationForest(contamination=0.05, random_state=42)
train_df['anomaly_score'] = iso.fit_predict(features)

anomalies = train_df[train_df['anomaly_score'] == -1]
print(f"Anomalies detected: {len(anomalies)} out of {len(train_df)}")

# Visualize anomaly scores
plt.figure(figsize=(8,4))
sns.countplot(x='anomaly_score', data=train_df, palette='Set1')
plt.title('Isolation Forest: Anomaly Detection (-1 = Anomaly)')
plt.show()

X_train = train_df.drop(['Churn', 'anomaly_score'], axis=1)
y_train = train_df['Churn']

X_test = test_df.drop('Churn', axis=1)
y_test = test_df['Churn']

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)
y_prob = rf.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred))
print(f"ROC-AUC Score: {roc_auc_score(y_test, y_prob):.4f}")

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['No Churn','Churn'],
            yticklabels=['No Churn','Churn'])
plt.title('Confusion Matrix')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.show()

fpr, tpr, _ = roc_curve(y_test, y_prob)
plt.plot(fpr, tpr, label=f'AUC = {roc_auc_score(y_test, y_prob):.2f}')
plt.plot([0,1],[0,1],'--', color='gray')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - Fraud/Risk Detection Model')
plt.legend()
plt.show()

importances = pd.Series(rf.feature_importances_, index=X_train.columns)
importances.sort_values(ascending=False).head(10).plot(kind='barh', color='teal')
plt.title('Top 10 Risk Factors (Feature Importance)')
plt.gca().invert_yaxis()
plt.show()

test_df['risk_score'] = y_prob
test_df['risk_level'] = pd.cut(test_df['risk_score'],
                                bins=[0, 0.3, 0.6, 1.0],
                                labels=['Low', 'Medium', 'High'])

print(test_df['risk_level'].value_counts())

sns.countplot(x='risk_level', data=test_df,
              order=['Low','Medium','High'], palette='RdYlGn_r')
plt.title('Customer Risk Level Distribution')
plt.show()