# -*- coding: utf-8 -*-
"""Codveda Predicitive Analysis ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxEll_VvX0s8K6kTUh5EvevT9YGoIYy5
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (accuracy_score, classification_report,
                             confusion_matrix, mean_squared_error, r2_score)
import warnings
warnings.filterwarnings('ignore')
print("All libraries loaded successfully!")

import pandas as pd

# Upload files first using the folder icon on the left
try:
    iris_df = pd.read_csv('1) iris.csv')
    train_df = pd.read_csv('churn-bigml-80.csv')
    test_df = pd.read_csv('churn-bigml-20.csv')

    # Correctly load house_df with space-separated values and no header
    house_df = pd.read_csv('4) house Prediction Data Set.csv', sep=r'\s+', header=None)
    column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
    house_df.columns = column_names

    print("Iris shape:", iris_df.shape)
    print("Churn train shape:", train_df.shape)
    print("Churn test shape:", test_df.shape)
    print("House shape:", house_df.shape)
    print("\nHouse columns:", house_df.columns.tolist())
except FileNotFoundError as e:
    print(f"Error: {e}")
    print("One or more CSV files could not be found. Please ensure the following files are uploaded to your Colab environment using the folder icon on the left sidebar and that their names match exactly:")
    print("  - '1) iris.csv'")
    print("  - 'churn-bigml-80.csv'")
    print("  - 'churn-bigml-20.csv'")
    print("  - '4) house Prediction Data Set.csv'")
    # Initialize empty dataframes to prevent further NameErrors in subsequent cells
    iris_df = pd.DataFrame()
    train_df = pd.DataFrame()
    test_df = pd.DataFrame()
    house_df = pd.DataFrame()

print("=" * 50)
print("PART 1: HOUSE PRICE REGRESSION")
print("=" * 50)

print(house_df.head())
print(house_df.info())
print(house_df.describe())

# Drop non-numeric columns if any
house_df = house_df.dropna()

# Encode categorical columns
le = LabelEncoder()
for col in house_df.select_dtypes(include='object').columns:
    house_df[col] = le.fit_transform(house_df[col])

# Define target - find the price column
print("Columns:", house_df.columns.tolist())

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder

# --- Start of fix: Re-load and preprocess house_df correctly within this cell ---
# This re-runs data loading and preprocessing to correct an upstream issue.
# In a typical notebook, the upstream cell (DVX2S2STeYiI) would be fixed directly.

try:
    # Reload house_df with correct parsing for space-separated data and no header
    house_df = pd.read_csv('4) house Prediction Data Set.csv', sep=r'\s+', header=None)

    # Assign standard Boston Housing dataset column names
    column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
    house_df.columns = column_names

    # Re-apply preprocessing steps from cell 9xWTJU-jfM7n
    house_df = house_df.dropna()

    # Encode categorical columns (will likely do nothing if all columns are now numeric)
    le = LabelEncoder()
    for col in house_df.select_dtypes(include='object').columns:
        house_df[col] = le.fit_transform(house_df[col])

    print("Reloaded and preprocessed house_df info:")
    house_df.info()

except FileNotFoundError:
    print("Error: '4) house Prediction Data Set.csv' not found. Please ensure it's uploaded.")
    house_df = pd.DataFrame() # Create empty to prevent further errors if file not found

# --- End of fix ---

# Check if house_df is empty after potential error or preprocessing
if house_df.empty:
    print("House DataFrame is empty or could not be loaded correctly. Cannot proceed with model training.")
else:
    # Set target column - explicitly set to 'MEDV' based on column names
    target_col = 'MEDV'
    print(f"Target column: {target_col}")

    # Ensure the target column exists before proceeding
    if target_col not in house_df.columns:
        print(f"Error: Target column '{target_col}' not found in DataFrame. Columns are: {house_df.columns.tolist()}")
    else:
        X_house = house_df.drop(target_col, axis=1)
        y_house = house_df[target_col]

        # Check if X_house is empty after dropping target column (should not be now)
        if X_house.empty:
            print("Error: Feature DataFrame (X_house) is empty after dropping the target column.")
        else:
            X_train_h, X_test_h, y_train_h, y_test_h = train_test_split(
                X_house, y_house, test_size=0.2, random_state=42)

            lr = LinearRegression()
            lr.fit(X_train_h, y_train_h)
            y_pred_h = lr.predict(X_test_h)

            mse = mean_squared_error(y_test_h, y_pred_h)
            r2 = r2_score(y_test_h, y_pred_h)

            print(f"Mean Squared Error: {mse:,.2f}")
            print(f"R² Score: {r2:.4f}")
            print(f"Model Accuracy: {r2*100:.2f}%")

plt.figure(figsize=(10, 5))
plt.scatter(y_test_h, y_pred_h, alpha=0.5, color='steelblue')
plt.plot([y_test_h.min(), y_test_h.max()],
         [y_test_h.min(), y_test_h.max()], 'r--', lw=2)
plt.xlabel('Actual Price')
plt.ylabel('Predicted Price')
plt.title(f'House Price: Actual vs Predicted (R² = {r2:.4f})')
plt.tight_layout()
plt.savefig('01_house_price_regression.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart 1 saved!")

print("=" * 50)
print("PART 2: CUSTOMER CHURN CLASSIFICATION")
print("=" * 50)

# Encode churn data
le = LabelEncoder()
for df in [train_df, test_df]:
    for col in df.select_dtypes(include='object').columns:
        df[col] = le.fit_transform(df[col])
    for col in df.select_dtypes(include='bool').columns:
        df[col] = df[col].astype(int)

X_train_c = train_df.drop('Churn', axis=1)
y_train_c = train_df['Churn']
X_test_c = test_df.drop('Churn', axis=1)
y_test_c = test_df['Churn']

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train_c, y_train_c)
y_pred_c = rf.predict(X_test_c)

print(classification_report(y_test_c, y_pred_c))
print(f"Accuracy: {accuracy_score(y_test_c, y_pred_c)*100:.2f}%")

cm = confusion_matrix(y_test_c, y_pred_c)
plt.figure(figsize=(7, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['No Churn', 'Churn'],
            yticklabels=['No Churn', 'Churn'])
plt.title('Churn Classification — Confusion Matrix')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.tight_layout()
plt.savefig('02_churn_confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart 2 saved!")

importances = pd.Series(rf.feature_importances_, index=X_train_c.columns)
importances.sort_values(ascending=False).head(10).plot(
    kind='barh', color='steelblue', figsize=(9, 6))
plt.title('Top 10 Features for Churn Prediction')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig('03_churn_feature_importance.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart 3 saved!")

print("=" * 50)
print("PART 3: IRIS SPECIES CLUSTERING (KMeans)")
print("=" * 50)

# Use only numerical columns
X_iris = iris_df[['sepal_length', 'sepal_width',
                   'petal_length', 'petal_width']]

scaler = StandardScaler()
X_iris_scaled = scaler.fit_transform(X_iris)

# Find optimal clusters using Elbow Method
inertia = []
K_range = range(1, 11)
for k in K_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X_iris_scaled)
    inertia.append(km.inertia_)

plt.figure(figsize=(8, 4))
plt.plot(K_range, inertia, 'bo-', markersize=8)
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Inertia')
plt.title('Elbow Method — Optimal Number of Clusters')
plt.tight_layout()
plt.savefig('04_elbow_method.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart 4 saved!")

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
iris_df['cluster'] = kmeans.fit_predict(X_iris_scaled)

# Plot clusters
plt.figure(figsize=(9, 6))
colors = ['#0078D4', '#E76C00', '#107C10']
species_list = iris_df['cluster'].unique()

for i, cluster in enumerate(sorted(species_list)):
    subset = iris_df[iris_df['cluster'] == cluster]
    plt.scatter(subset['petal_length'], subset['petal_width'],
                label=f'Cluster {cluster}',
                color=colors[i], alpha=0.7, s=60)

plt.xlabel('Petal Length (cm)')
plt.ylabel('Petal Width (cm)')
plt.title('KMeans Clustering — Iris Dataset (K=3)')
plt.legend()
plt.tight_layout()
plt.savefig('05_iris_clustering.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart 5 saved!")

le2 = LabelEncoder()
iris_df['species_encoded'] = le2.fit_transform(iris_df['species'])

print("Cluster vs Actual Species comparison:")
print(pd.crosstab(iris_df['cluster'],
                  iris_df['species'],
                  rownames=['Cluster'],
                  colnames=['Species']))

print("\n" + "="*50)
print("LEVEL 3 TASK 1 — SUMMARY OF RESULTS")
print("="*50)
print(f"1. House Price Regression  → R² Score: {r2:.4f} ({r2*100:.1f}% accuracy)")
print(f"2. Churn Classification    → Accuracy: {accuracy_score(y_test_c, y_pred_c)*100:.2f}%")
print(f"3. Iris Clustering         → 3 clusters identified matching 3 species")
print("\nAll 5 charts saved successfully!")
print("Download the .ipynb file: File → Download → Download .ipynb")